### ISSUE TITLE
Scythe of the white eyed one missing

### ISSUE THREAD

**Issue by Dream-Master** [KryptonCaptain/ThaumicBases#4]
@KryptonCaptain The Scythe of the white eyed one is removed in the lastest build. Any reason why?

**Comment by KryptonCaptain** [comment]
Scythe was one of the first things removed in my branch, and hasn't ever been in any of my builds.
TBases has its fair share of unbalanced things, but it doesn't need unbalanced meme trash.

**Comment by Dream-Master** [comment]
Thanks for info.
