### ISSUE TITLE
Thaumcraft Mobs killed by Extra Utilities Spikes crash the Server

### ISSUE THREAD

**Issue by Dream-Master** [KryptonCaptain/ThaumicBases#5]
I reported this issue another player have on my Server.

``DFliyerz commented 21 hours ago
Killing a thaumcraft mob with spikes means thaumic bases will freak out and crash Thaumcraft, rendering it impossible to use for all players until the server is restarted.``

``DFliyerz commented 10 hours ago
I think so, after removing my spikes from my mob grinder it stopped crashing.``

https://gist.github.com/DFliyerz/55b2ce7102ad1ca55f5cd59cf27e454f

Orgininal Issue:
https://github.com/GTNewHorizons/NewHorizons/issues/1187

Pack :
https://github.com/GTNewHorizons/NewHorizons/

**Comment by KryptonCaptain** [comment]
Should be resolved on latest build

**Comment by Dream-Master** [comment]
Cool thanks will test it later.
