### ISSUE TITLE
Small bug with knowledge seeds.

### ISSUE THREAD

**Issue by OneEyeMaker** [KryptonCaptain/ThaumicBases#6]
Hello, @KryptonCaptain !
Great thanks for your work! I'm using your version of Thaumic Bases for my private modpack.
Found small bug in original mod, which aren't fixed yet.
Knwoledge (Rosa Mysteria) seeds often can't be planted when some mods are present.
Some mods (for example, Railcraft) replace some air block with it's own analogues (in case of Railcraft it is [Residual Heat block](https://github.com/CovertJaguar/Railcraft/blob/mc-1.7.10/src/main/java/mods/railcraft/common/blocks/hidden/BlockHidden.java)). That prevents planting Rosa Mysteria seeds.
Please, replace ```block == Blocks.air``` to ```block.isAir()``` or (better) ```world.isAirBlock(block)``` here:
https://github.com/KryptonCaptain/ThaumicBases/blob/master/src/main/java/tb/common/item/ItemKnoseSeeds.java#L28
I didn't check, but I guess, that another seeds/plants (or other blocks) may have the same problem.

Again, thank you *very much* for your work!
P. S. Sorry for my English. I'm from Russia.

**Comment by KryptonCaptain** [comment]
I'm glad you're enjoying my version of the mod. It is a pleasant surprise to discover other people using it, so thank you. Reporting things like this, even little bugs, both improve the mod and help me learn new or better ways to do things.

`world.isAirBlock()` is what I've gone with, and that seems to work - though personally, I normally disable Railcraft's residual heat blocks, as it is a very underused feature that creates a lot of tileEntities it probably doesn't need to for tracking players.
