### ISSUE TITLE
Advanced Alchemical Furnace

### ISSUE THREAD

**Issue by Fortist** [KryptonCaptain/ThaumicBases#7]
For some reason, it doesnt output to anything while burning things, which with alumentum (whatever) takes a while for it to cool down.
Alembics or Essentia interfaces (Thaumic energistics) dont seem to pull it until cooled.

**Comment by KryptonCaptain** [comment]
Tried break and replace? Seems obvious, but gotta ask.

If not, can you provide more information, pics of the setup, modlist, etc? I have it working fine in the dev environment and my thaumcraft addon test instance, so not sure why it would be doing that.

**Comment by Fortist** [comment]
Break and replace? yeah, sure. move it and tried it twice.
I already have the Super alchemical furnace, so at this point it's kinda moot.

The set up is the furnace, by itself, and alembics on top.
Then the furnace with bellows and alembics
Then the furnace with Thaumic Energistic's providers/imports/exports, with and without alembics.

Modlist is too long to list, or Im just too lazy at the moment to get it together. I'll do some troubleshooting later to shave it down.

**Comment by Fortist** [comment]
Also, Particles crash with your TTinkerer fork.

And my modlist, if you really wanna look through it.

https://pastebin.com/gTbZri9N

**Comment by KryptonCaptain** [comment]
Closed because hopefully fixed now
